language: rust
sudo: required

after_success: curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: nDz1woOuCXUzmgeiCbzcWSpcaGiuso7jfdg7oF6yQGjGn2blD8yBGpSgZcczKnRblXctU6cPU8ulQcyVpGQmh7oqTBkprWOPrZXjQaQHoy8jYHKNgQRIKcdZH/ErTvI74RkAtUFy9dNPHrM9cHhSEtbPBLCkCaJZcD71TO0hRvI90Wvx/RlrCMdVfPlUCK4ZqzEV9k5+sOyNFSf8KFoJe4paANdPJuWWzX7rcqNkNWcl+hcsKK5AFeBYvMlY2n45/UmrHmtNNSOR+4X+K0jmJMbN0IC0jGvOZY8Jrrl53VWF7GUMTOvtwM5eg6cpgks+6Mn3GKPbFwp2jeeRbb8yjQu9LOYZptfLcTvnDpMBNRyVq2Dr7/EB4mNHs2UfOIzHGAtqsgipt1vMQaAotFv3vEYqCwalcmZ+A3jaBekaOjzYzU4gCv3n8M52uSSKoy1Po5ofq/Sy85Xt6Tq6lUc2654kP2MvwRoNaMjxqp3PeeNDbyB1zTEJxl+Bm/CZx4q49iZlHsWsYcz/SzFjB8QgrCSYusjRWjlCvUz+Gkc3P6KjJ08by1+JJJnwoSuacRvN4PeeoMGo+0zqRy93mq2Ht55Dp4R1P5HgjbmLu6EuWLUk1I7w+Izo78YFK8Ho6XZunvx+dhrC9x5MP4m7tjx3NGURXmJm8wxzl0elRdLcib8=

notifications:
  email: false
