[package]
name = "random"
version = "0.1.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/random"
homepage = "https://github.com/stainless-steel/random"
documentation = "https://stainless-steel.github.io/random"
description = "The package provides means of generating random numbers."

[dev-dependencies]
assert = "*"
