[package]
name = "random"
version = "0.5.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/random"
homepage = "https://github.com/stainless-steel/random"
documentation = "https://stainless-steel.github.io/random"
description = "The package provides sources of randomness."

[dependencies]
probability = "*"
