[package]
name = "random"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/random"
homepage = "https://github.com/hilbert-space/random"
description = "Random."
